services:
  opensearch:
    image: opencrvs-toppan-opensearch:v${VERSION}
    container_name: opencrvs-toppan-opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=WelcomeDemo1.23@
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.0.0
    container_name: opencrvs-toppan-dashboards
    environment:
      OPENSEARCH_HOSTS: 'http://opensearch:9200'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
    depends_on:
      - opensearch
    ports:
      - '5601:5601'

  toppan-data-seeder:
    image: opencrvs-toppan-seeder:v${VERSION}
    depends_on:
      - opensearch
    volumes:
      - ./init/opensearch:/init
    command: ["bash", "/init/toppan-data-seeder.sh"]

  person_registry_pg:
    image: postgres:15
    container_name: opencrvs-toppan-postgres
    environment:
      POSTGRES_DB: person_registry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - person_registry_pgdata:/var/lib/postgresql/data
      - ./init/pgsql:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'

  pg_adminer:
    image: adminer
    container_name: opencrvs-toppan-adminer
    ports:
      - '15432:8080'

volumes:
  opensearch-data:
  person_registry_pgdata: